import { readFile } from "node:fs/promises";
import path from "node:path";

import {
  PDFDocument,
  PDFFont,
  PDFImage,
  PDFPage,
  StandardFonts,
  rgb,
  type RGB,
} from "pdf-lib";

import { MAX_MARK, PASS_MARK, gradeScaleLegend } from "@/lib/grading";
import {
  SCHOOL_PROFILE,
  type ReportCardData,
  type SequenceMark,
  type SubjectLine,
} from "@/lib/report-card";

/**
 * Report card template — A4 portrait term report card.
 *
 * Structure (kept identical from page to page, close to the printed
 * Cameroonian secondary-school term report card):
 *
 *   ┌ outer double border ──────────────────────────────────────────────┐
 *   │ logo        school header (name, address, motto)      year/term   │
 *   │                  ── TERM REPORT CARD ──                           │
 *   │ student information block (name, matricule, class, parent, rank)  │
 *   │ subjects table: per sequence CA1 / CA2 / Exam / Average, then      │
 *   │                 term average, coefficient points, grade, remark    │
 *   │ term summary + class performance + attendance                      │
 *   │ remarks (class teacher, principal) + promotion decision            │
 *   │ signatures (class teacher, academic master, principal) + date      │
 *   │ footer: generated by GradeFlow · page x of y                       │
 *   └───────────────────────────────────────────────────────────────────┘
 *
 * Everything printed comes from ReportCardData, which is read from
 * PostgreSQL. Values the school itself must supply (letterhead, motto,
 * principal's name) come from the SCHOOL_* environment variables — see
 * SCHOOL_PROFILE in lib/report-card.ts.
 */

/* =========================================================
   PAGE GEOMETRY (A4 portrait, points)
========================================================= */

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;

const BORDER_OUTER = 18;
const BORDER_INNER = 22;
const LEFT = 33;
const RIGHT = PAGE_WIDTH - 33;
const CONTENT_WIDTH = RIGHT - LEFT;

const COLORS = {
  ink: rgb(0.1, 0.1, 0.12),
  muted: rgb(0.42, 0.44, 0.5),
  rule: rgb(0.65, 0.66, 0.72),
  brand: rgb(0.36, 0.14, 0.62),
  headerFill: rgb(0.92, 0.9, 0.96),
  groupFill: rgb(0.86, 0.83, 0.93),
  bandFill: rgb(0.96, 0.95, 0.98),
  zebra: rgb(0.975, 0.975, 0.98),
  white: rgb(1, 1, 1),
  warn: rgb(0.65, 0.3, 0.05),
};

/* =========================================================
   TEXT HELPERS
========================================================= */

/** Keeps only characters the standard PDF fonts can encode. */
function safeText(value: unknown): string {
  return String(value ?? "")
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/[\u201C\u201D\u201E]/g, '"')
    .replace(/[\u2013\u2014\u2212]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\u00A0/g, " ")
    .replace(/[^\u0020-\u00FF]/g, "")
    .trim();
}

function fitText(text: string, font: PDFFont, size: number, maxWidth: number) {
  const value = safeText(text);

  if (!value || font.widthOfTextAtSize(value, size) <= maxWidth) return value;

  let result = value;

  while (
    result.length > 1 &&
    font.widthOfTextAtSize(`${result}...`, size) > maxWidth
  ) {
    result = result.slice(0, -1);
  }

  return `${result}...`;
}

function wrapText(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number,
  maxLines = 3
): string[] {
  const words = safeText(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;

    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate;
      continue;
    }

    if (current) lines.push(current);
    current = word;

    if (lines.length === maxLines) break;
  }

  if (current && lines.length < maxLines) lines.push(current);

  return lines.length ? lines : [""];
}

/** Formats a mark: whole numbers stay whole, decimals keep 2 digits. */
function mark(value: number | null | undefined): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";

  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

function average(value: number | null | undefined): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";

  return value.toFixed(2);
}

function shortDate(value: string | Date | null | undefined): string {
  if (!value) return "—";

  const date = typeof value === "string" ? new Date(value) : value;

  if (Number.isNaN(date.getTime())) return "—";

  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

/* =========================================================
   DRAWING PRIMITIVES (top-down coordinates)
========================================================= */

type Fonts = {
  regular: PDFFont;
  bold: PDFFont;
  italic: PDFFont;
  boldItalic: PDFFont;
};

type Pen = {
  page: PDFPage;
  fonts: Fonts;
};

function baseline(top: number, size: number) {
  return PAGE_HEIGHT - top - size * 0.82;
}

function drawText(
  pen: Pen,
  value: string,
  options: {
    x: number;
    top: number;
    size: number;
    font?: PDFFont;
    color?: RGB;
    width?: number;
    align?: "left" | "center" | "right";
  }
) {
  const font = options.font ?? pen.fonts.regular;
  const text = options.width
    ? fitText(value, font, options.size, options.width)
    : safeText(value);

  if (!text) return;

  let x = options.x;

  if (options.align && options.width) {
    const textWidth = font.widthOfTextAtSize(text, options.size);

    if (options.align === "center") x = options.x + (options.width - textWidth) / 2;
    if (options.align === "right") x = options.x + options.width - textWidth;
  }

  pen.page.drawText(text, {
    x,
    y: baseline(options.top, options.size),
    size: options.size,
    font,
    color: options.color ?? COLORS.ink,
  });
}

function drawBox(
  pen: Pen,
  box: {
    left: number;
    top: number;
    width: number;
    height: number;
    fill?: RGB;
    border?: RGB;
    borderWidth?: number;
  }
) {
  pen.page.drawRectangle({
    x: box.left,
    y: PAGE_HEIGHT - box.top - box.height,
    width: box.width,
    height: box.height,
    color: box.fill,
    borderColor: box.border,
    borderWidth: box.border ? (box.borderWidth ?? 0.6) : undefined,
  });
}

function drawRule(
  pen: Pen,
  options: {
    left: number;
    top: number;
    width: number;
    color?: RGB;
    thickness?: number;
  }
) {
  pen.page.drawLine({
    start: { x: options.left, y: PAGE_HEIGHT - options.top },
    end: { x: options.left + options.width, y: PAGE_HEIGHT - options.top },
    thickness: options.thickness ?? 0.6,
    color: options.color ?? COLORS.rule,
  });
}

/* =========================================================
   LOGO
========================================================= */

let cachedLogo: Uint8Array | null | undefined;

/**
 * Reads the school logo once per process. The paths are static literals so
 * the production build can trace them; when no logo file exists the report
 * card header is simply drawn without one.
 */
async function loadLogo(): Promise<Uint8Array | null> {
  if (cachedLogo !== undefined) return cachedLogo;

  cachedLogo = null;

  try {
    cachedLogo = await readFile(
      path.join(process.cwd(), "public", "images", "logo.png")
    );

    return cachedLogo;
  } catch {
    /* the PNG logo is missing — try the JPEG one */
  }

  try {
    cachedLogo = await readFile(
      path.join(process.cwd(), "public", "images", "logo.jpg")
    );
  } catch {
    cachedLogo = null;
  }

  return cachedLogo;
}

/** Embeds the logo once per PDF document and reuses it on every page. */
async function embedLogo(doc: PDFDocument): Promise<PDFImage | null> {
  const bytes = await loadLogo();

  if (!bytes) return null;

  try {
    return await doc.embedPng(bytes);
  } catch {
    return null;
  }
}

/* =========================================================
   SECTIONS
========================================================= */

function drawPageFrame(pen: Pen) {
  drawBox(pen, {
    left: BORDER_OUTER,
    top: BORDER_OUTER,
    width: PAGE_WIDTH - BORDER_OUTER * 2,
    height: PAGE_HEIGHT - BORDER_OUTER * 2,
    border: COLORS.brand,
    borderWidth: 1.4,
  });

  drawBox(pen, {
    left: BORDER_INNER,
    top: BORDER_INNER,
    width: PAGE_WIDTH - BORDER_INNER * 2,
    height: PAGE_HEIGHT - BORDER_INNER * 2,
    border: COLORS.brand,
    borderWidth: 0.4,
  });
}

function drawHeader(pen: Pen, card: ReportCardData, logo: PDFImage | null) {
  const top = 34;

  if (logo) {
    try {
      const height = 52;
      const width = (logo.width / logo.height) * height;

      pen.page.drawImage(logo, {
        x: LEFT,
        y: PAGE_HEIGHT - top - height,
        width,
        height,
      });
    } catch {
      /* a missing logo must never break the report card */
    }
  }

  const centerX = LEFT;
  const centerWidth = CONTENT_WIDTH;

  if (SCHOOL_PROFILE.ministry) {
    drawText(pen, SCHOOL_PROFILE.ministry, {
      x: centerX,
      top: top - 2,
      size: 6.8,
      color: COLORS.muted,
      width: centerWidth,
      align: "center",
    });
  }

  drawText(pen, SCHOOL_PROFILE.name.toUpperCase(), {
    x: centerX,
    top: top + 8,
    size: 14.5,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: centerWidth,
    align: "center",
  });

  const addressLine = [
    SCHOOL_PROFILE.address,
    SCHOOL_PROFILE.phone && `Tel: ${SCHOOL_PROFILE.phone}`,
    SCHOOL_PROFILE.email,
  ]
    .filter(Boolean)
    .join("  ·  ");

  if (addressLine) {
    drawText(pen, addressLine, {
      x: centerX,
      top: top + 26,
      size: 7,
      color: COLORS.muted,
      width: centerWidth,
      align: "center",
    });
  }

  if (SCHOOL_PROFILE.motto) {
    drawText(pen, `"${SCHOOL_PROFILE.motto}"`, {
      x: centerX,
      top: top + 37,
      size: 7,
      font: pen.fonts.italic,
      color: COLORS.muted,
      width: centerWidth,
      align: "center",
    });
  }

  /* academic context on the right of the letterhead */

  drawText(pen, `Academic Year: ${card.classroom.academicYearName}`, {
    x: RIGHT - 150,
    top: top + 4,
    size: 7.6,
    font: pen.fonts.bold,
    width: 150,
    align: "right",
  });

  drawText(pen, `Term: ${card.term.name}`, {
    x: RIGHT - 150,
    top: top + 15,
    size: 7.6,
    font: pen.fonts.bold,
    width: 150,
    align: "right",
  });

  /* title band */

  const bandTop = top + 50;
  const bandHeight = 17;

  drawBox(pen, {
    left: LEFT,
    top: bandTop,
    width: CONTENT_WIDTH,
    height: bandHeight,
    fill: COLORS.brand,
  });

  drawText(pen, "TERM REPORT CARD", {
    x: LEFT,
    top: bandTop + 4.5,
    size: 9.5,
    font: pen.fonts.bold,
    color: COLORS.white,
    width: CONTENT_WIDTH,
    align: "center",
  });

  return bandTop + bandHeight + 9;
}

function drawStudentBlock(pen: Pen, card: ReportCardData, top: number) {
  const height = 76;
  const half = CONTENT_WIDTH / 2;

  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height,
    fill: COLORS.bandFill,
    border: COLORS.rule,
  });

  pen.page.drawLine({
    start: { x: LEFT + half, y: PAGE_HEIGHT - top },
    end: { x: LEFT + half, y: PAGE_HEIGHT - top - height },
    thickness: 0.4,
    color: COLORS.rule,
  });

  const rows = [
    [
      ["Student's Name", card.student.fullName],
      ["Matricule", card.student.matricule],
    ],
    [
      ["Class", card.classroom.name],
      ["Section", card.classroom.sectionName ?? "—"],
    ],
    [
      [
        "Parent / Guardian",
        card.student.parentName ?? "Not linked",
      ],
      ["Class size", `${card.class.size} students`],
    ],
  ];

  const padding = 8;
  const labelWidth = 78;
  const valueWidth = half - padding * 2 - labelWidth;

  rows.forEach((row, index) => {
    const rowTop = top + 9 + index * 18;

    row.forEach(([label, value], column) => {
      const x = LEFT + column * half + padding;

      drawText(pen, `${label}:`, {
        x,
        top: rowTop,
        size: 7.4,
        color: COLORS.muted,
        width: labelWidth,
      });

      drawText(pen, value, {
        x: x + labelWidth,
        top: rowTop,
        size: 8,
        font: pen.fonts.bold,
        width: valueWidth,
      });
    });
  });

  /* status line — suspended / dismissed students are visibly flagged */

  const statusText = card.student.enrolled
    ? `Status: ACTIVE — enrolled for ${card.classroom.academicYearName}`
    : `Status: ${card.student.statusLabel.toUpperCase()} — historical record, not currently enrolled`;

  drawRule(pen, {
    left: LEFT + 1,
    top: top + height - 16,
    width: CONTENT_WIDTH - 2,
    color: COLORS.rule,
    thickness: 0.4,
  });

  drawText(pen, statusText, {
    x: LEFT + padding,
    top: top + height - 12,
    size: 7.2,
    font: card.student.enrolled ? pen.fonts.regular : pen.fonts.bold,
    color: card.student.enrolled ? COLORS.muted : COLORS.warn,
    width: CONTENT_WIDTH - padding * 2,
  });

  return top + height + 11;
}

/* =========================================================
   SUBJECTS TABLE
========================================================= */

type Column = { key: string; label: string; width: number; align?: "left" | "center" | "right" };

function columnsFor(card: ReportCardData): Column[] {
  const sequenceColumns = card.sequences.flatMap((sequence) => [
    {
      key: `${sequence.id}-ca1`,
      label: "CA1",
      width: 25,
      align: "center" as const,
    },
    {
      key: `${sequence.id}-ca2`,
      label: "CA2",
      width: 25,
      align: "center" as const,
    },
    {
      key: `${sequence.id}-exam`,
      label: "Exam",
      width: 27,
      align: "center" as const,
    },
    {
      key: `${sequence.id}-avg`,
      label: "Avg",
      width: 29,
      align: "center" as const,
    },
  ]);

  const fixed: Column[] = [
    { key: "subject", label: "SUBJECT", width: 0, align: "left" },
    { key: "coefficient", label: "Coef", width: 26, align: "center" },
    ...sequenceColumns,
    { key: "termAverage", label: "Term Avg", width: 38, align: "center" },
    { key: "points", label: "Coef×Avg", width: 40, align: "center" },
    { key: "grade", label: "Grade", width: 28, align: "center" },
    { key: "remark", label: "Remarks", width: 0, align: "left" },
  ];

  const fixedWidth = fixed.reduce((sum, column) => sum + column.width, 0);
  const remaining = CONTENT_WIDTH - fixedWidth;
  const remarkWidth = Math.max(72, Math.min(110, remaining * 0.42));
  const subjectWidth = remaining - remarkWidth;

  return fixed.map((column) => {
    if (column.key === "subject") return { ...column, width: subjectWidth };
    if (column.key === "remark") return { ...column, width: remarkWidth };
    return column;
  });
}

function tableHeader(pen: Pen, card: ReportCardData, columns: Column[], top: number) {
  const groupHeight = 11;
  const labelHeight = 12;
  const totalHeight = groupHeight + labelHeight;

  /* group header */

  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height: groupHeight,
    fill: COLORS.groupFill,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  let x = LEFT;

  drawText(pen, `SUBJECTS — ${card.term.name.toUpperCase()}`, {
    x: LEFT + 4,
    top: top + 2.6,
    size: 6.6,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: columns[0].width,
  });

  x = LEFT + columns[0].width + columns[1].width;

  card.sequences.forEach((sequence) => {
    const width = columns
      .filter((column) => column.key.startsWith(`${sequence.id}-`))
      .reduce((sum, column) => sum + column.width, 0);

    drawText(pen, `${sequence.name.toUpperCase()} (out of 20)`, {
      x,
      top: top + 2.6,
      size: 6.4,
      font: pen.fonts.bold,
      color: COLORS.brand,
      width,
      align: "center",
    });

    x += width;
  });

  drawText(pen, "TERM RESULT", {
    x: x + 34,
    top: top + 2.6,
    size: 6.4,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: columns
      .filter((column) =>
        ["termAverage", "points", "grade"].includes(column.key)
      )
      .reduce((sum, column) => sum + column.width, 0),
    align: "center",
  });

  /* column labels */

  const labelTop = top + groupHeight;

  drawBox(pen, {
    left: LEFT,
    top: labelTop,
    width: CONTENT_WIDTH,
    height: labelHeight,
    fill: COLORS.headerFill,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  let labelX = LEFT;

  for (const column of columns) {
    drawText(pen, column.label, {
      x: labelX + 2,
      top: labelTop + 3.4,
      size: 5.9,
      font: pen.fonts.bold,
      width: column.width - 6,
      align: column.align === "left" ? "left" : "center",
    });

    labelX += column.width;
  }

  return top + totalHeight;
}

function subjectCells(card: ReportCardData, line: SubjectLine): Record<string, string> {
  const cells: Record<string, string> = {
    subject: line.subject,
    coefficient: String(line.coefficient),
    termAverage: average(line.average),
    points: average(line.points),
    grade: line.grade ?? "—",
    remark: line.remark ?? "—",
  };

  for (const sequence of line.sequences) {
    cells[`${sequence.sequenceId}-ca1`] = mark(sequence.ca1);
    cells[`${sequence.sequenceId}-ca2`] = mark(sequence.ca2);
    cells[`${sequence.sequenceId}-exam`] = mark(sequence.exam);
    cells[`${sequence.sequenceId}-avg`] = average(sequence.average);
  }

  return cells;
}

function drawSubjectRow(
  pen: Pen,
  card: ReportCardData,
  line: SubjectLine,
  columns: Column[],
  top: number,
  striped: boolean
) {
  const height = 25;

  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height,
    fill: striped ? COLORS.zebra : COLORS.white,
    border: COLORS.rule,
    borderWidth: 0.4,
  });

  const cells = subjectCells(card, line);

  let x = LEFT;

  for (const column of columns) {
    if (column.key === "subject") {
      drawText(pen, cells.subject, {
        x: x + 4,
        top: top + 4,
        size: 7.8,
        font: pen.fonts.bold,
        width: column.width - 8,
      });

      if (line.teacher) {
        drawText(pen, `Teacher: ${line.teacher}`, {
          x: x + 4,
          top: top + 14.5,
          size: 6.1,
          font: pen.fonts.italic,
          color: COLORS.muted,
          width: column.width - 8,
        });
      }

      x += column.width;
      continue;
    }

    drawText(pen, cells[column.key] ?? "—", {
      x: x + 3,
      top: top + 8.5,
      size: 7.4,
      width: column.width - 6,
      align: column.align === "left" ? "left" : "center",
    });

    x += column.width;
  }

  return top + height;
}

function drawTotalsRow(
  pen: Pen,
  card: ReportCardData,
  columns: Column[],
  top: number
) {
  const height = 20;

  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height,
    fill: COLORS.headerFill,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  drawText(pen, "TOTAL", {
    x: LEFT + 4,
    top: top + 6.5,
    size: 7.8,
    font: pen.fonts.bold,
    width: columns[0].width - 8,
  });

  let x = LEFT + columns[0].width;

  drawText(pen, String(card.totals.coefficients), {
    x: x + 3,
    top: top + 6.5,
    size: 7.8,
    font: pen.fonts.bold,
    width: columns[1].width - 6,
    align: "center",
  });

  x += columns[1].width;

  /* One total per sequence: the points earned (Σ average × coefficient),
     which is the figure that feeds the term average. */
  card.sequences.forEach((sequence) => {
    const sequenceWidth = columns
      .filter((column) => column.key.startsWith(`${sequence.id}-`))
      .reduce((sum, column) => sum + column.width, 0);

    const recorded = card.subjects
      .map((line) => ({
        coefficient: line.coefficient,
        mark: line.sequences.find((entry) => entry.sequenceId === sequence.id),
      }))
      .filter(
        (row): row is { coefficient: number; mark: SequenceMark } =>
          Boolean(row.mark) && row.mark?.average !== null
      );

    const points = recorded.reduce(
      (sum, row) => sum + (row.mark.average ?? 0) * row.coefficient,
      0
    );

    const coefficients = recorded.reduce(
      (sum, row) => sum + row.coefficient,
      0
    );

    const sequenceAverage = coefficients ? points / coefficients : null;

    drawText(
      pen,
      recorded.length
        ? `${points.toFixed(2)} pts  (avg ${average(sequenceAverage)})`
        : "—",
      {
        x,
        top: top + 6.5,
        size: 6.6,
        font: pen.fonts.bold,
        color: COLORS.brand,
        width: sequenceWidth,
        align: "center",
      }
    );

    x += sequenceWidth;
  });

  const termAverageColumn = columns.find((column) => column.key === "termAverage");
  const pointsColumn = columns.find((column) => column.key === "points");
  const gradeColumn = columns.find((column) => column.key === "grade");

  drawText(pen, average(card.totals.average), {
    x: x + 3,
    top: top + 6.5,
    size: 8,
    font: pen.fonts.bold,
    width: (termAverageColumn?.width ?? 38) - 6,
    align: "center",
  });
  x += termAverageColumn?.width ?? 38;

  drawText(pen, average(card.totals.points), {
    x: x + 3,
    top: top + 6.5,
    size: 7.8,
    font: pen.fonts.bold,
    width: (pointsColumn?.width ?? 40) - 6,
    align: "center",
  });
  x += pointsColumn?.width ?? 40;

  drawText(pen, card.totals.grade ?? "—", {
    x: x + 3,
    top: top + 6.5,
    size: 8,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: (gradeColumn?.width ?? 28) - 6,
    align: "center",
  });
  x += gradeColumn?.width ?? 28;

  drawText(pen, `Pos. ${card.class.position ?? "—"}/${card.class.ranked}`, {
    x: x + 4,
    top: top + 6.5,
    size: 6.8,
    font: pen.fonts.bold,
    width: RIGHT - x - 4,
  });

  return top + height;
}

/* =========================================================
   SUMMARY BLOCKS
========================================================= */

function drawSummaryBlock(
  pen: Pen,
  title: string,
  rows: [string, string][],
  box: { left: number; top: number; width: number; height: number }
) {
  drawBox(pen, {
    left: box.left,
    top: box.top,
    width: box.width,
    height: box.height,
    fill: COLORS.white,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  drawBox(pen, {
    left: box.left,
    top: box.top,
    width: box.width,
    height: 12,
    fill: COLORS.headerFill,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  drawText(pen, title, {
    x: box.left + 4,
    top: box.top + 3,
    size: 6.6,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: box.width - 8,
  });

  rows.forEach(([label, value], index) => {
    const rowTop = box.top + 17 + index * 14;

    drawText(pen, label, {
      x: box.left + 5,
      top: rowTop,
      size: 7,
      color: COLORS.muted,
      width: box.width * 0.58,
    });

    drawText(pen, value, {
      x: box.left + box.width * 0.58,
      top: rowTop,
      size: 7.4,
      font: pen.fonts.bold,
      width: box.width * 0.42 - 6,
      align: "right",
    });
  });

  return box.top + box.height;
}

function drawRemarksBlock(
  pen: Pen,
  card: ReportCardData,
  top: number
) {
  const height = 78;

  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height,
    fill: COLORS.white,
    border: COLORS.rule,
    borderWidth: 0.5,
  });

  const half = CONTENT_WIDTH / 2;

  pen.page.drawLine({
    start: { x: LEFT + half, y: PAGE_HEIGHT - top },
    end: { x: LEFT + half, y: PAGE_HEIGHT - top - height },
    thickness: 0.4,
    color: COLORS.rule,
  });

  drawText(pen, "CLASS TEACHER'S REMARK", {
    x: LEFT + 5,
    top: top + 5,
    size: 6.6,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: half - 10,
  });

  const teacherRemark = wrapText(
    card.classTeacherRemark ?? "No remark recorded for this term.",
    pen.fonts.regular,
    7.2,
    half - 12,
    3
  );

  teacherRemark.forEach((line, index) => {
    drawText(pen, line, {
      x: LEFT + 5,
      top: top + 17 + index * 10,
      size: 7.4,
    });
  });

  drawText(pen, "PRINCIPAL'S REMARK", {
    x: LEFT + half + 5,
    top: top + 5,
    size: 6.6,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: half - 10,
  });

  const principalRemark = wrapText(
    card.principalRemark ?? "Report card generated from the marks recorded in the school database.",
    pen.fonts.regular,
    7.2,
    half - 12,
    2
  );

  principalRemark.forEach((line, index) => {
    drawText(pen, line, {
      x: LEFT + half + 5,
      top: top + 17 + index * 10,
      size: 7.4,
    });
  });

  drawText(
    pen,
    `Promotion decision: ${card.decision ?? (card.student.enrolled ? "—" : "Not applicable (not enrolled)")}`,
    {
      x: LEFT + half + 5,
      top: top + 52,
      size: 7.8,
      font: pen.fonts.bold,
      color: card.decision === "REPEAT" ? COLORS.warn : COLORS.brand,
      width: half - 10,
    }
  );

  if (card.marks.missing > 0) {
    drawText(
      pen,
      `Marks recorded for this term: ${card.marks.recorded} of ${card.marks.expected}.`,
      {
        x: LEFT + 5,
        top: top + 57,
        size: 6.8,
        font: pen.fonts.italic,
        color: COLORS.muted,
        width: half - 10,
      }
    );
  } else {
    drawText(pen, "All expected marks are recorded for this term.", {
      x: LEFT + 5,
      top: top + 57,
      size: 6.6,
      font: pen.fonts.italic,
      color: COLORS.muted,
      width: half - 10,
    });
  }

  return top + height + 6;
}

function drawGradingLegend(pen: Pen, top: number) {
  drawBox(pen, {
    left: LEFT,
    top,
    width: CONTENT_WIDTH,
    height: 20,
    fill: COLORS.bandFill,
    border: COLORS.rule,
    borderWidth: 0.4,
  });

  drawText(pen, "GRADING SCALE", {
    x: LEFT + 5,
    top: top + 3,
    size: 6.2,
    font: pen.fonts.bold,
    color: COLORS.brand,
    width: CONTENT_WIDTH - 10,
  });

  drawText(
    pen,
    `${gradeScaleLegend()}      Pass mark: ${PASS_MARK}/${MAX_MARK}`,
    {
      x: LEFT + 5,
      top: top + 10.5,
      size: 6.6,
      color: COLORS.muted,
      width: CONTENT_WIDTH - 10,
    }
  );

  return top + 20 + 8;
}

function drawSignatures(pen: Pen, top: number) {
  const blocks = [
    "Class Teacher",
    SCHOOL_PROFILE.academicMasterName
      ? `Academic Master (${SCHOOL_PROFILE.academicMasterName})`
      : "Academic Master",
    SCHOOL_PROFILE.principalName
      ? `Principal (${SCHOOL_PROFILE.principalName})`
      : "Principal",
  ];

  const width = CONTENT_WIDTH / blocks.length;

  blocks.forEach((label, index) => {
    const x = LEFT + index * width;

    drawText(pen, label, {
      x: x + 4,
      top,
      size: 6.8,
      color: COLORS.muted,
      width: width - 8,
      align: "center",
    });

    drawRule(pen, {
      left: x + 10,
      top: top + 22,
      width: width - 20,
      color: COLORS.ink,
      thickness: 0.6,
    });

    drawText(pen, "Signature & date", {
      x: x + 4,
      top: top + 25,
      size: 6,
      color: COLORS.muted,
      width: width - 8,
      align: "center",
    });
  });

  return top + 36;
}

/* =========================================================
   PAGE COMPOSITION
========================================================= */

function drawReportCardPage(
  doc: PDFDocument,
  card: ReportCardData,
  fonts: Fonts,
  logo: PDFImage | null,
  pageNumber: number,
  totalPages: number
) {
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const pen: Pen = { page, fonts };

  drawPageFrame(pen);

  let top = drawHeader(pen, card, logo);

  top = drawStudentBlock(pen, card, top);

  const columns = columnsFor(card);

  top = tableHeader(pen, card, columns, top);

  card.subjects.forEach((line, index) => {
    top = drawSubjectRow(pen, card, line, columns, top, index % 2 === 1);
  });

  top = drawTotalsRow(pen, card, columns, top);

  top += 12;

  const half = (CONTENT_WIDTH - 8) / 2;

  const summaryHeight = 12 + 4 * 14 + 6;

  drawSummaryBlock(
    pen,
    "TERM SUMMARY",
    [
      ["Total coefficients", String(card.totals.coefficients)],
      ["Total points (Coef × Avg)", average(card.totals.points)],
      ["Term average / 20", average(card.totals.average)],
      ["Grade", card.totals.grade ?? "—"],
    ],
    { left: LEFT, top, width: half, height: summaryHeight }
  );

  drawSummaryBlock(
    pen,
    "CLASS PERFORMANCE",
    [
      ["Class average", average(card.class.average)],
      ["Highest average", average(card.class.highest)],
      ["Lowest average", average(card.class.lowest)],
      [
        "Position",
        card.class.position ? `${card.class.position} of ${card.class.ranked}` : "—",
      ],
    ],
    { left: LEFT + half + 8, top, width: half, height: summaryHeight }
  );

  top += summaryHeight + 8;

  const attendanceHeight = 12 + 4 * 14 + 6;

  drawSummaryBlock(
    pen,
    "ATTENDANCE / DISCIPLINE (TERM)",
    [
      ["Present", `${card.attendance.PRESENT} h`],
      ["Absent", `${card.attendance.ABSENT} h`],
      ["Late", `${card.attendance.LATE} h`],
      ["Excused", `${card.attendance.EXCUSED} h`],
    ],
    { left: LEFT, top, width: half, height: attendanceHeight }
  );

  drawSummaryBlock(
    pen,
    "ENROLMENT",
    [
      ["Academic year", card.classroom.academicYearName],
      ["Term", card.term.name],
      ["Status", card.student.statusLabel],
      ["Attendance rate", card.attendance.rate === null ? "—" : `${card.attendance.rate}%`],
    ],
    { left: LEFT + half + 8, top, width: half, height: attendanceHeight }
  );

  top += attendanceHeight + 8;

  top = drawRemarksBlock(pen, card, top);

  top = drawGradingLegend(pen, top);

  top = drawSignatures(pen, top);

  /* footer */

  drawRule(pen, { left: LEFT, top, width: CONTENT_WIDTH, color: COLORS.rule });

  drawText(
    pen,
    `Generated by GradeFlow from the marks, attendance and results stored in the school database on ${shortDate(card.generatedAt)}.`,
    {
      x: LEFT,
      top: top + 4,
      size: 6.2,
      color: COLORS.muted,
      width: CONTENT_WIDTH * 0.72,
    }
  );

  drawText(pen, `Page ${pageNumber} of ${totalPages}`, {
    x: LEFT + CONTENT_WIDTH * 0.72,
    top: top + 4,
    size: 6.2,
    color: COLORS.muted,
    width: CONTENT_WIDTH * 0.28,
    align: "right",
  });
}

async function loadFonts(doc: PDFDocument): Promise<Fonts> {
  return {
    regular: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
    italic: await doc.embedFont(StandardFonts.HelveticaOblique),
    boldItalic: await doc.embedFont(StandardFonts.HelveticaBoldOblique),
  };
}

/* =========================================================
   PUBLIC API
========================================================= */

/** Renders one student's report card as an A4 portrait PDF. */
export async function renderReportCardPdf(
  card: ReportCardData
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const fonts = await loadFonts(doc);
  const logo = await embedLogo(doc);

  doc.setTitle(
    `Report card — ${card.student.fullName} — ${card.term.name} ${card.classroom.academicYearName}`
  );
  doc.setAuthor(SCHOOL_PROFILE.name);
  doc.setSubject(`${card.classroom.name} · ${card.term.name}`);

  drawReportCardPage(doc, card, fonts, logo, 1, 1);

  return doc.save();
}

/**
 * Renders a class set of report cards: one page per student, in the order
 * given (the class list order), inside a single PDF document.
 */
export async function renderReportCardsPdf(
  cards: ReportCardData[]
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const fonts = await loadFonts(doc);
  const logo = await embedLogo(doc);

  doc.setTitle(
    cards.length
      ? `${cards[0].classroom.name} report cards — ${cards[0].term.name} ${cards[0].classroom.academicYearName}`
      : "Report cards"
  );
  doc.setAuthor(SCHOOL_PROFILE.name);

  for (let index = 0; index < cards.length; index += 1) {
    drawReportCardPage(doc, cards[index], fonts, logo, index + 1, cards.length);
  }

  return doc.save();
}

/** File name used for a class set, e.g. Form3A_Report_Cards_2026_2027.pdf */
export function classReportCardFileName(
  classroomName: string,
  academicYearName: string
) {
  const clean = (value: string) => value.replace(/[^A-Za-z0-9]+/g, "_");

  return `${clean(classroomName)}_Report_Cards_${clean(academicYearName.replace("/", "_"))}.pdf`;
}

/** File name used for one student, e.g. Report_Card_John_Doe_First_Term.pdf */
export function studentReportCardFileName(card: ReportCardData) {
  const clean = (value: string) => value.replace(/[^A-Za-z0-9]+/g, "_");

  return `Report_Card_${clean(card.student.fullName)}_${clean(card.term.name)}_${clean(
    card.classroom.academicYearName.replace("/", "_")
  )}.pdf`;
}
