"use client";

import { useCallback, useEffect, useState } from "react";
import { Award, FileText, Loader2, TrendingUp } from "lucide-react";

import Sidebar from "@/components/parent/SideBar";
import Navbar from "@/components/parent/NavBar";
import ChildSelector from "@/components/parent/ChildSelector";

type ReportCard = {
  id: string;
  term: string;
  average: number;
  rank: number | null;
  decision: string | null;
  principalRemark: string | null;
  createdAt: string;
};

type ChildReport = {
  student: { id: string; name: string; class: string | null };
  reportCards: ReportCard[];
};

export default function ParentReportCardsPage() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [childId, setChildId] = useState<string | null>(null);
  const [data, setData] = useState<ChildReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const loadReportCards = useCallback(async (studentId: string) => {
    try {
      setLoading(true);
      setError("");

      const response = await fetch(
        `/api/parent/results?studentId=${encodeURIComponent(studentId)}`,
        { cache: "no-store" }
      );

      const payload = await response.json();

      if (!response.ok) {
        throw new Error(payload.error || "Failed to load the report cards.");
      }

      setData(payload);
    } catch (err) {
      console.error("Parent Report Cards Error:", err);

      setError(
        err instanceof Error ? err.message : "Failed to load the report cards."
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (childId) loadReportCards(childId);
  }, [childId, loadReportCards]);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <Sidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} />

      <div className="min-h-screen lg:pl-72">
        <Navbar
          onMenuClick={() => setSidebarOpen(true)}
          title="Report Cards"
          subtitle="Term report cards of your children."
        />

        <main className="p-5 sm:p-8">
          <div className="mx-auto max-w-4xl">
            <div className="mb-8">
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                Report Cards
              </h1>

              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Term averages, class ranks and the principal's decision for each
                report card generated by the school.
              </p>
            </div>

            <ChildSelector selectedId={childId} onSelect={setChildId} />

            {error && (
              <div className="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900/50 dark:bg-red-950/20 dark:text-red-400">
                {error}
              </div>
            )}

            {loading && (
              <div className="flex min-h-[200px] items-center justify-center">
                <div className="flex items-center gap-3 text-gray-500 dark:text-gray-400">
                  <Loader2 size={22} className="animate-spin" />
                  <span className="text-sm">Loading report cards...</span>
                </div>
              </div>
            )}

            {!loading && data && childId && (
              <>
                {data.reportCards.length === 0 ? (
                  <div className="rounded-2xl border border-gray-200 bg-white p-10 text-center dark:border-gray-800 dark:bg-gray-900">
                    <FileText
                      size={40}
                      className="mx-auto text-gray-300 dark:text-gray-600"
                    />

                    <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
                      No report card has been generated yet. They appear here
                      after the end-of-term processing.
                    </p>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                    {data.reportCards.map((card) => (
                      <article
                        key={card.id}
                        className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-purple-100 text-purple-700 dark:bg-purple-950/40 dark:text-purple-300">
                            <FileText size={20} />
                          </div>

                          {card.decision && (
                            <span
                              className={`rounded-lg px-2.5 py-1 text-xs font-bold ${
                                card.decision === "PROMOTED"
                                  ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"
                                  : "bg-red-100 text-red-700 dark:bg-red-950/40 dark:text-red-300"
                              }`}
                            >
                              {card.decision}
                            </span>
                          )}
                        </div>

                        <h2 className="mt-4 text-base font-bold text-gray-900 dark:text-white">
                          {card.term}
                        </h2>

                        <p className="text-xs text-gray-400">
                          Generated on{" "}
                          {new Date(card.createdAt).toLocaleDateString("en-GB", {
                            day: "numeric",
                            month: "long",
                            year: "numeric",
                          })}
                        </p>

                        <div className="mt-4 grid grid-cols-2 gap-3">
                          <div className="rounded-xl bg-gray-50 p-3 text-center dark:bg-gray-950">
                            <p className="text-xs text-gray-400">Average</p>

                            <p
                              className={`mt-1 text-xl font-bold ${
                                card.average >= 10
                                  ? "text-emerald-600 dark:text-emerald-400"
                                  : "text-red-600 dark:text-red-400"
                              }`}
                            >
                              {card.average}/20
                            </p>
                          </div>

                          <div className="rounded-xl bg-gray-50 p-3 text-center dark:bg-gray-950">
                            <p className="text-xs text-gray-400">Rank</p>

                            <p className="mt-1 text-xl font-bold text-gray-900 dark:text-white">
                              {card.rank ? `#${card.rank}` : "—"}
                            </p>
                          </div>
                        </div>

                        {card.principalRemark && (
                          <p className="mt-4 rounded-xl bg-purple-50 p-3 text-xs italic text-purple-800 dark:bg-purple-950/20 dark:text-purple-300">
                            “{card.principalRemark}”
                          </p>
                        )}
                      </article>
                    ))}
                  </div>
                )}
              </>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
